use artgallerysystem;
select * from product;
select * from reviews;
select * from checkout;
select * from history;
select * from messages;
alter table messages modify message_id int;
alter table checkout add return_date varchar(45);
alter table checkout rename column addtocart_date to checkout_date;
insert into reviews values(101,"mohit@gmail.com",Now(),5.0,3,"good");
insert into reviews values(102,"arsh@gmail.com",Now(),4.5,1,"awesome");
insert into product values(1,"Crystal","Ankita","Digital Art",10,7,"Digital Art","");
insert into product values(2,"AutumnPathWay","Ankita","Spray Art",10,7,"Spray Art","");
insert into product values(3,"TraditionalArt","Ankita","Mandala Art",10,7,"Mandala Art","");
insert into product values(4,"Puzzle","Ankita","Digital Art",10,7,"Digital Art","");
insert into product values(5,"WalkInThePark","Ankita","Mandala Art",10,7,"Mandala Art","");
insert into product values(6,"WomanWithPeacock","Ankita","Spray Art",10,7,"Spray Art","");
alter table reviews change column review_id review_id int(20) null;
insert into checkout values(201, "mohit@gmail.com",now(),3,now());
set SQL_SAFE_UPDATES=0;
delete from checkout WHERE return_date=null;
set SQL_SAFE_UPDATES=1;